---
title: "Sistemas discretos lineales de primer y segundo orden"
author: "Miguel Conde"
date: "27 de febrero de 2017"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      fig.align = "center")
```

```{r}
source("dftFUNs.R")
```


## Primer orden
Sea el sistema LTI:

$$
y[n] - ay[n-1] = x[n], \qquad |a| < 1
$$


Su respuesta en frecuencia es:
$$
H(e^{j\omega}) = \frac{1}{1-ae^{-j\omega}}
$$
y su respuesta al impulso es:
$$
h[n] = a^n u[n]
$$
De manera que la respuesta al escalón es:
$$
s[n] = h[n]*u[n] = \frac{1-a^{n+1}}{1-a} u[n]
$$


```{r}
h1 <- function(n, a) {
  if (n >= 0)
    return(a^n)
  return(0)
}

toRange_n <- function(n_range, mFUN, ...) {
  sapply(n_range, mFUN, ...)
}

toRange_n(-10:10, h1, 0.9)
```

```{r}
plot_toRange_n <- function(n_range = -10:10, mFUN, ...) {
  plot(n_range, toRange_n(n_range, mFUN, ...), type = "h", lwd = 3,
       xaxt = "n", bty = "l",
       xlab = "n", ylab = "", main = paste("a = ", parse(text = list(...))))
  axis(side = 1, at = n_range, labels = format(n_range))
}

n_range <- -20:20
layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = FALSE))
plot_toRange_n(n_range, h1, a =  1/4)
plot_toRange_n(n_range, h1, a = -1/4)
plot_toRange_n(n_range, h1, a =  1/2)
plot_toRange_n(n_range, h1, a = -1/2)

layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = FALSE))
plot_toRange_n(n_range, h1, a =  3/4)
plot_toRange_n(n_range, h1, a = -3/4)
plot_toRange_n(n_range, h1, a =  7/8)
plot_toRange_n(n_range, h1, a = -7/8)

```

Ahora la respuesta al escalón: 

```{r}
plot_s1_n <- function(K = 100, a = 1/2) {
  n_range <- -K:K
  l_range <- (-2*K):(2*K)
  plot(l_range, signal::conv(toRange_n(n_range, h1, a), 
                             toRange_n(n_range, stepFUN)),
       type = "h", lwd = 2, xaxt = "n", xlim = c(-K/8, K/4),
       xlab = "n", ylab = "s[n]",
       main = paste("a = ", a))
  axis(side = 1, at = l_range, labels = format(l_range))  
}

layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = FALSE))
plot_s1_n(K = 100, a =  1/4)
plot_s1_n(K = 100, a = -1/4)
plot_s1_n(K = 100, a =  1/2)
plot_s1_n(K = 100, a = -1/2)

layout(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = FALSE))
plot_s1_n(K = 100, a =  3/4)
plot_s1_n(K = 100, a = -3/4)
plot_s1_n(K = 100, a =  7/8)
plot_s1_n(K = 100, a = -7/8)
```

Transformada de la respuesta al impulso o función característica del sistema

```{r}
H1 <- function(range_w, a = 1/2) {
  return(1 / (1 - a * complex(modulus = 1, 
                              argument = -range_w)))
}

range_labs_w <- (-4:4) * 0.5 * pi

xlabels <- sapply(range_labs_w / pi, function(x){
  if (x == 0)
    return("0")
  if (x == 1)
    return(expression(pi))
  if (x == -1)
    return(expression(paste("-" * pi)))
  s <- paste0("expression(paste(", x, "* pi))")
  return(eval(parse(text = s)))
})

range_w <- seq(-pi, pi, by = 0.01)

plot(range_w, 20*log10(Mod(H1(range_w, a = 7/8))),
     type = "l", xaxt = "n",
     ylab = expression(paste("|H(", plain(e)^{j*omega}, ")| dB")),
     xlab = expression(omega))
axis(side = 1, at = range_labs_w, 
     labels = (xlabels))

lines(range_w, 20*log10(Mod(H1(range_w, a = 3/4))),
     type = "l", col = "blue")
lines(range_w, 20*log10(Mod(H1(range_w, a = 1/2))),
     type = "l", col = "red")
lines(range_w, 20*log10(Mod(H1(range_w, a = 1/4))),
     type = "l", col = "green")

abline(v = 0, lty = 2)
abline(v = -pi, lty = 3)
abline(v = pi, lty = 3)
abline(h = 0, lty = 2)

legend("topleft", legend = c("a = 7/8", "a = 3/4", "a = 1/2", "a = 1/4"),
       bty = "n", col = c("black", "blue", "red", "green"), lty = 1)
```

```{r}
plot(range_w, Arg(H1(range_w, a = 7/8)),
     type = "l", xaxt = "n", yaxt = "n",
     ylab = expression(paste("Arg(H(", plain(e)^{j*omega}, "))")),
     xlab = expression(omega))
axis(side = 1, at = range_labs_w, 
     labels = (xlabels))
axis(side = 2, at = c(-pi/2, -pi/4, pi/4, pi/2), 
     labels = expression(-pi/2, -pi/4, pi/4, pi/2))

lines(range_w, Arg(H1(range_w, a = 3/4)),
     type = "l", col = "blue")
lines(range_w, Arg(H1(range_w, a = 1/2)),
     type = "l", col = "red")
lines(range_w, Arg(H1(range_w, a = 1/4)),
     type = "l", col = "green")

abline(v = 0, lty = 2)
abline(v = -pi, lty = 3)
abline(v = pi, lty = 3)
abline(h = 0, lty = 2)

legend("topright", legend = c("a = 7/8", "a = 3/4", "a = 1/2", "a = 1/4"),
       bty = "n", col = c("black", "blue", "red", "green"), lty = 1)
```

Con a < 0
```{r}
plot(range_w, 20*log10(Mod(H1(range_w, a = -7/8))),
     type = "l", xaxt = "n",
     ylab = expression(paste("|H(", plain(e)^{j*omega}, ")| dB")),
     xlab = expression(omega))
axis(side = 1, at = range_labs_w, 
     labels = (xlabels))

lines(range_w, 20*log10(Mod(H1(range_w, a = -3/4))),
     type = "l", col = "blue")
lines(range_w, 20*log10(Mod(H1(range_w, a = -1/2))),
     type = "l", col = "red")
lines(range_w, 20*log10(Mod(H1(range_w, a = -1/4))),
     type = "l", col = "green")

abline(v = 0, lty = 2)
abline(v = -pi, lty = 3)
abline(v = pi, lty = 3)
abline(h = 0, lty = 2)

legend(x = -2, y = 15, legend = c("a = -7/8", "a = -3/4", "a = -1/2", "a = -1/4"),
       bty = "n", col = c("black", "blue", "red", "green"), lty = 1)
```


```{r}
plot(range_w, Arg(H1(range_w, a = -7/8)),
     type = "l", xaxt = "n", yaxt = "n",
     ylab = expression(paste("Arg(H(", plain(e)^{j*omega}, "))")),
     xlab = expression(omega))
axis(side = 1, at = range_labs_w, 
     labels = (xlabels))
axis(side = 2, at = c(-pi/2, -pi/4, pi/4, pi/2), 
     labels = expression(-pi/2, -pi/4, pi/4, pi/2))

lines(range_w, Arg(H1(range_w, a = -3/4)),
     type = "l", col = "blue")
lines(range_w, Arg(H1(range_w, a = -1/2)),
     type = "l", col = "red")
lines(range_w, Arg(H1(range_w, a = -1/4)),
     type = "l", col = "green")

abline(v = 0, lty = 2)
abline(v = -pi, lty = 3)
abline(v = pi, lty = 3)
abline(h = 0, lty = 2)

legend("topleft", legend = c("a = -7/8", "a = -3/4", "a = -1/2", "a = -1/4"),
       bty = "n", col = c("black", "blue", "red", "green"), lty = 1)
```



